channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.2
- pip:
  - mlflow==2.17.0
  - cffi==1.17.1
  - cloudpickle==3.1.0
  - defusedxml==0.7.1
  - graphviz==0.20.3
  - lightgbm==4.5.0
  - matplotlib==3.9.2
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==5.9.0
  - pyarrow==17.0.0
  - scikit-learn==1.1.3
  - scipy==1.10.0
name: mlflow-env
